/* Database schema to keep the structure of entire database. */

CREATE TABLE OWNERS (
    id INT GENERATED ALWAYS AS IDENTITY,
    full_name VARCHAR,
    age INT,
    PRIMARY KEY (id)
);

CREATE TABLE SPECIES (
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR,
    PRIMARY KEY (id)
);

CREATE TABLE ANIMALS (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR,
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL,
    species_id INT,
    owner_id INT,
    PRIMARY KEY (id),  
    CONSTRAINT species_key
        FOREIGN KEY (species_id)
            REFERENCES species(id),
    CONSTRAINT owner_key
        FOREIGN KEY (owner_id)
            REFERENCES owners(id)             
);

CREATE TABLE VETS (
    id INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    name VARCHAR,
    age INT,
    date_of_graduation DATE,
    PRIMARY KEY (id)
);

CREATE TABLE SPECIALIZATION (
    species_id INT,
    vets_id INT,
    CONSTRAINT species_key
        FOREIGN KEY (species_id)
            REFERENCES species(id),
    CONSTRAINT vets_key
        FOREIGN KEY (vets_id)
            REFERENCES vets(id)        
);

CREATE TABLE VISITS (
    animal_id INT,
    vets_id INT,
    date_of_visit DATE,
    CONSTRAINT animals_key
        FOREIGN KEY (animal_id)
            REFERENCES animals(id),
    CONSTRAINT vets_key
        FOREIGN KEY (vets_id)
            REFERENCES vets(id)        
);