/* Database schema to keep the structure of entire database. */

CREATE TABLE OWNERS (
    id INT GENERATED ALWAYS AS IDENTITY,
    full_name VARCHAR,
    age INT,
    PRIMARY KEY (id)
);

CREATE TABLE SPECIES (
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR,
    PRIMARY KEY (id)
);

CREATE TABLE ANIMALS (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR,
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL,
    species_id INT,
    owner_id INT,
    PRIMARY KEY (id),  
    CONSTRAINT species_key
        FOREIGN KEY (species_id)
            REFERENCES species(id),
    CONSTRAINT owner_key
        FOREIGN KEY (owner_id)
            REFERENCES owners(id)             
);
